name: NextGen
version: 1.4
main: io.codejava.mc.nextgen.NextGen
api-version: '1.21'
author: CodeJava
description: The player who picks up the dragon egg wins!
commands:
  nextgen:
    description: Main command for NextGen.
    usage: /nextgen [start|reload|abort|border]
    permission: nextgen.admin
