name: Build Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the correct Java version (JDK 25)
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          # UPDATED: Changed from '21' to '25'
          java-version: '25'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NextGen-Plugin
          path: target/*.jar